<div class="related-container">
    <div class="related-title">延伸閱讀：</div>
    <a href="https://www.mirrormedia.mg/projects/political-contribution/" target="_blank">
        <div class="related-content">
            <span class="related-link-text">
                <div>數讀政治獻金</div>
                <div>立委金主大解密！</div>
            </span>
            <span class="related-link-img"></span>
        </div>
    </a>
</div>
