<div class="related-container">
    <div class="related-title">此批資料已經全數辨識完畢並公開：</div>
    <a href="https://www.readr.tw/project/political-contribution" target="_blank">
        <div class="related-content">
            <span class="related-link-text">
                <div>數讀政治獻金 2.0</div>
                <div>翻開立委（八年份）的金主投資名冊</div>
            </span>
            <span class="related-link-img"></span>
        </div>
    </a>
</div>
