<?= $this->partial('/common/header.phtml', $this) ?>
<div class="container">
    <div class="jumbotron">
        <h2>政治獻金數位化</h2>
        <span class="lead">鄉民一起來</span>
        <a class="btn btn-primary btn-medium" href="/cell">+1 »</a>
        <p></p>
        <div>目前資料已經有 <span id="counter" class="lead"><?= $this->count ?></span> 筆</div>
    </div>
    <hr>
    <div class="row-fluid">
        <h3>API</h3>
        <h5>取得指定頁所有欄位的值</h5>
        <code>http://campaign-finance.g0v.ctiml.tw/api/getcells/1100</code>
        <h5>取得單一欄位的值</h5>
        <code>http://campaign-finance.g0v.ctiml.tw/api/getcellvalue/1100/8/1</code>
        <h5>取得已經處理完成的頁面列表(<?= count(PageDone::search(1)) ?> / 2637)</h5>
        <code>http://campaign-finance.g0v.ctiml.tw/api/getdonepages</code>
    </div>
    <hr>
    <div class="row-fluid">
        <h5>資料來源：Ronny Wang</h5>
        <a href="http://ronnywang.pixnet.net/blog/post/40488349">抓出政治獻金掃描文件中的每一個欄位</a>
    </div>
</div>
<a href="https://github.com/ctiml/campaign-finance.g0v.ctiml.tw"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"></a>
<script src="/static/js/index.js"></script>
<?= $this->partial('/common/footer.phtml', $this) ?>
