<?= $this->partial('/common/header.phtml', $this) ?>
<div class="container">
    <div class="jumbotron">
        <h2>政治獻金數位化</h2>
        <span class="lead">鄉民一起來</span>
        <a class="btn btn-primary btn-medium" href="/cell">+1 »</a>
        <p></p>
        <div>目前資料已經有 <span id="counter" class="lead"><?= $this->count ?></span> 筆，還有 <span id="todo" class="lead"></span> 筆未輸入</div>
        <p></p>
        <div><a class="btn btn-primary btn-medium" href="/cell">十萬鄉民十萬軍，鄉民一起追獻金</a></div>
    </div>
    <hr>
    <div class="alert alert-warning">本站政治獻金資料收集僅供學術交流使用，嚴禁營利、徵信，或其他不正當目的之使用</div>
    <div class="row-fluid">
        <h3>政治獻金認領及圖檔上傳回報</h3>
            <p style="font-size: 16px; margin-bottom: 25px">把你掃描的 pdf 圖檔放上 Google Drive, Dropbox, mega 等網路空間，提供連結讓我們下載。所有上傳為匿名。</p>
            <p class="lead">目前認領進度 <a href="http://bit.ly/ScanProgress" target="_blank">http://bit.ly/ScanProgress</a> （第 8 屆立委優先）</p>
            <p class="lead">已上傳圖檔處理現況 <a href="http://bit.ly/ScanPoliticalContribution" target="_blank">http://bit.ly/ScanPoliticalContribution</a></p>
            <p class="lead"><a href="https://docs.google.com/forms/d/108LkUakP8qC5G3AGXMaX8t8d7yklf05M_PBphUqe6vg/viewform?edit_requested=true" target="_blank">政治獻金圖檔上傳回報表</a></p>
    </div>
    <hr>
    <div class="row-fluid">
        <h3>API</h3>
        <h5>取得指定頁所有欄位的值</h5>
        <code>http://campaign-finance.g0v.ctiml.tw/api/getcells/345</code>
        <h5>取得單一欄位的值</h5>
        <code>http://campaign-finance.g0v.ctiml.tw/api/getcellvalue/345/6/7</code>
        <h5>取得已經處理完成的頁面列表(<?= count(PageDone::search(1)) ?> / <?= count(PageInfo::search(1)) ?>)</h5>
        <code>http://campaign-finance.g0v.ctiml.tw/api/getdonepages</code>
    </div>
    <hr>
    <div class="row-fluid">
        <h5>資料來源：Ronny Wang</h5>
        <a href="http://ronnywang.pixnet.net/blog/post/40488349">抓出政治獻金掃描文件中的每一個欄位</a>
        <p></p>
        <div class="author" style="color: #bbb">
            <a style="color: #9be" target="_blank" href="http://ctiml.tw">@ctiml</a> / Timothy Lee
        </div>
    </div>
</div>
<a href="https://github.com/ctiml/campaign-finance.g0v.ctiml.tw"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"></a>
<script src="/static/js/index.js"></script>
<?= $this->partial('/common/footer.phtml', $this) ?>
