<div id="data-tab-list" class="data-tab">
<table id="datagrid"></table>
<div id="navGrid"></div>
</div>
<script language="javascript">
<?php if (strlen($this->set->getEAV('columns')) < 1000) { ?>
    var colNames = <?= json_encode(json_Decode($this->set->getEAV('columns'))) ?>;
<?php } ?>
var colModel = [];
for (var i = 0; i < colNames.length; i ++) {
    colModel.push({name:i, index:i, width:55});
    colNames[i] = (i + 1) + '.' + colNames[i];
}
var jqGridOptions = {
url:'/user/getdata/<?= $this->set->set_id ?>',
        datatype: "json",
        colNames:colNames,
        cellEdit: true,
        colModel:colModel,
        rowNum:100,
        rowList:[10,15,20,25,30,35,40],
        pager: '#navGrid',
        sortname: '0',
        sortorder: "asc",
        height: '400px',
        autowidth: true,
        viewrecords: true,
        caption: <?= json_encode($this->set->getEAV('title')) ?>
};
jQuery("#datagrid").jqGrid(jqGridOptions);
jQuery("#datagrid").jqGrid('navGrid','#navGrid',{edit:false,add:false,del:false});
</script>
