<?php

$data_set = DataSet::find($this->set->getEAV('data_from'));

?>
<button id="btn-tab-list">Show Data</button>
<button id="btn-tab-map">Show Map</button>
<?= $this->partial('/user/blob_csv.phtml', array('set' => $data_set)) ?>
<div 
    id="data-tab-map"
    class="data-tab"
    style="display:none;width:100%;height:400px"
    data-boundary="<?= $this->escape($this->set->getEAV('boundary')) ?>"
    data-wms-url="<?= getenv('CDN_PREFIX') ?>/wms?Request=GetMap&Layers=<?= urlencode($this->set->getLayerID()) ?>"
    data-clickzone-url="<?= getenv('CDN_PREFIX') ?>/wms?Request=GetClickZone&Layers=<?= urlencode($this->set->getLayerID()) ?>"
    data-click-url="/user/getdatafrompoint/?layer=<?= urlencode($this->set->getLayerID()) ?>"
></div>
