<?php

$this->body_class = 'user_import';
?>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Github Map+</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script src="/static/main.js?v=<?= getenv('STATIC_VERSION') ?>"></script>
<script type="text/javascript">
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
<?php } ?>
</script>
</head>
<body class="<?= $this->body_class ?>">
<p>
Do you want to import this file to GitHub Map+? <button id="btn-import-csv" data-wording-importing="importing..."
    data-import-link="/user/importcsv?user=<?= urlencode($this->user) ?>&repository=<?= urlencode($this->repository) ?>&path=<?= urlencode($this->path) ?>&branch=<?= urlencode($this->branch) ?>&commit=<?= urlencode($this->commit) ?>">Import</button>
</p>
Support file format: GeoJSON, TopoJSON, CSV
</body>
</html>
