<?php
$this->body_class = 'user_tree';
$this->params = array(
    'user' => $this->user,
    'repository' => $this->repository,
    'path' => $this->path,
    'branch' => $this->branch,
);
?>
<?= $this->partial('common/header.phtml', $this); ?>
<?= $this->partial('user/header.phtml', $this) ?>
<hr>
<table class="table" id="file-table">
</table>
<?= $this->partial('common/footer.phtml', $this); ?>
