        <div class="qa-group">
            <button class="btn quick-answer" id="btn-anonymous-donate" data-answer="匿名捐贈" tabindex="4">匿名捐贈</button>
            <button class="btn quick-answer" data-answer="個人捐贈收入" tabindex="5">個人捐贈收入</button>
            <button class="btn quick-answer" data-answer="交通旅運支出" tabindex="6">交通旅運支出</button>
            <button class="btn quick-answer" data-answer="人事費用支出" tabindex="7">人事費用支出</button>
            <button class="btn quick-answer" data-answer="人民團體捐贈收入" tabindex="8">人民團體捐贈收入</button>
        </div>
        <div class="qa-group">
            <button class="btn quick-answer" data-answer="租用宣傳車輛支出" tabindex="9">租用宣傳車輛支出</button>
            <button class="btn quick-answer" data-answer="營利事業捐贈收入" tabindex="10">營利事業捐贈收入</button>
            <button class="btn quick-answer" data-answer="公共關係費用支出" tabindex="11">公共關係費用支出</button>
            <button class="btn quick-answer" data-answer="雜支支出" tabindex="12">雜支支出</button>
            <button class="btn quick-answer" data-answer="宣傳支出" tabindex="13">宣傳支出</button>
            <button class="btn quick-answer" data-answer="集會支出" tabindex="14">集會支出</button>
        </div>
