        <?php $tabindex = 4 ?>
        <div class="qa-group">
            <button class="btn quick-answer" data-answer="是" tabindex="<?= $tabindex++ ?>">是</button>
            <button class="btn quick-answer" data-answer="匿名" tabindex="<?= $tabindex++ ?>">匿名</button>
            <button class="btn quick-answer" data-answer="匿名捐贈" tabindex="<?= $tabindex++ ?>">匿名捐贈</button>
            <button class="btn quick-answer" data-answer="個人捐贈收入" tabindex="<?= $tabindex++ ?>">個人捐贈收入</button>
            <button class="btn quick-answer" data-answer="交通旅運支出" tabindex="<?= $tabindex++ ?>">交通旅運支出</button>
            <button class="btn quick-answer" data-answer="人事費用支出" tabindex="<?= $tabindex++ ?>">人事費用支出</button>
            <button class="btn quick-answer" data-answer="人民團體捐贈收入" tabindex="<?= $tabindex++ ?>">人民團體捐贈收入</button>
        </div>
        <div class="qa-group">
            <button class="btn quick-answer" data-answer="租用宣傳車輛支出" tabindex="<?= $tabindex++ ?>">租用宣傳車輛支出</button>
            <button class="btn quick-answer" data-answer="營利事業捐贈收入" tabindex="<?= $tabindex++ ?>">營利事業捐贈收入</button>
            <button class="btn quick-answer" data-answer="公共關係費用支出" tabindex="<?= $tabindex++ ?>">公共關係費用支出</button>
            <button class="btn quick-answer" data-answer="雜支支出" tabindex="<?= $tabindex++ ?>">雜支支出</button>
            <button class="btn quick-answer" data-answer="宣傳支出" tabindex="<?= $tabindex++ ?>">宣傳支出</button>
            <button class="btn quick-answer" data-answer="集會支出" tabindex="<?= $tabindex++ ?>">集會支出</button>
        </div>
