<?= $this->partial('/common/header.phtml', $this) ?>
<div class="container">
    <h3>請填入圖片中的數字或文字</h3>
    <input id="ans" class="form-control" type="text" name="ans" />
    <a id="submit" class="btn btn-primary submit">送出</a>
    <a id="next">下一張</a>
    <span class="tip">Enter: 送出 / shift+Enter: 下一張</span>
    <div class="cell-info" data-page="<?= $this->page ?>" data-x="<?= $this->x ?>" data-y="<?= $this->y ?>">
        <?= "第 " . $this->page . " 頁 (" . $this->x . ", " . $this->y . ")" ?>
    </div>
    <div class="cell-image"><img src="<?= $this->cellimg ?>" /></div>
</div>
<script src="/static/js/cell.js"></script>
<link rel="stylesheet" href="/static/css/cell.css">
<?= $this->partial('/common/footer.phtml', $this) ?>
