<?= $this->partial('/common/header.phtml', $this) ?>
<div class="container">
    <h3>請填入圖片中的數字、文字或日期</h3>
    <input id="ans" class="form-control" type="text" name="ans" />
    <a id="submit" class="btn btn-primary submit">送出</a>
    <a id="next">下一張</a>
    <span class="tip">Enter: 送出 / shift+Enter: 下一張</span>
    <label><input id="no-content" type="checkbox" />這張圖片沒有內容</label>
    <div class="cell-info"></div>
    <div class="cell-image"></div>
</div>
<script src="/static/js/cell.js"></script>
<link rel="stylesheet" href="/static/css/cell.css">
<?= $this->partial('/common/footer.phtml', $this) ?>
