<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width"/>
<meta property="og:title" content="數讀政治獻金 鄉民一起來"/>
<meta property="og:description" content="雖然行政院已經允諾修法，要邁向真正的公開透明，還得看立委們在這個屆期願不願意讓法案三讀。為了不讓「趙敏在大都等張無忌」的悲劇再次發生，g0v 政治獻金透明化專案復活啦！鍵盤解密立委金主，就差你一個！"/>
<meta property="og:image" content="https://campaign-finance.g0v.ctiml.tw/static/img/ogimage.png">
<meta property="og:url" content="https://campaign-finance.g0v.ctiml.tw">
<title>政治獻金數位化</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/bootstrap.min.js"></script>
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = 'https://www.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php } ?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/css/bootstrap.css">
<link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
